tTriangleR1 = csvread('/mnt/dados/Meus Documentos/Estudo/Mestrado/Repositório/trunk/Material pesquisa/Leituras de sensores/Controle/Rotação dos motores/Entradas/throttle-triangleFunction-stable-rotor1.csv')
tTriangleR2 = csvread('/mnt/dados/Meus Documentos/Estudo/Mestrado/Repositório/trunk/Material pesquisa/Leituras de sensores/Controle/Rotação dos motores/Entradas/throttle-triangleFunction-stable-rotor2.csv')
tTriangleR3 = csvread('/mnt/dados/Meus Documentos/Estudo/Mestrado/Repositório/trunk/Material pesquisa/Leituras de sensores/Controle/Rotação dos motores/Entradas/throttle-triangleFunction-stable-rotor3.csv')
tTriangleR4 = csvread('/mnt/dados/Meus Documentos/Estudo/Mestrado/Repositório/trunk/Material pesquisa/Leituras de sensores/Controle/Rotação dos motores/Entradas/throttle-triangleFunction-stable-rotor4.csv')
rTriangleR1 = csvread('/mnt/dados/Meus Documentos/Estudo/Mestrado/Repositório/trunk/Material pesquisa/Leituras de sensores/Controle/Rotação dos motores/Saídas/revolutions-triangleFunction-stable-rotor1.csv')
rTriangleR2 = csvread('/mnt/dados/Meus Documentos/Estudo/Mestrado/Repositório/trunk/Material pesquisa/Leituras de sensores/Controle/Rotação dos motores/Saídas/revolutions-triangleFunction-stable-rotor2.csv')
rTriangleR3 = csvread('/mnt/dados/Meus Documentos/Estudo/Mestrado/Repositório/trunk/Material pesquisa/Leituras de sensores/Controle/Rotação dos motores/Saídas/revolutions-triangleFunction-stable-rotor3.csv')
rTriangleR4 = csvread('/mnt/dados/Meus Documentos/Estudo/Mestrado/Repositório/trunk/Material pesquisa/Leituras de sensores/Controle/Rotação dos motores/Saídas/revolutions-triangleFunction-stable-rotor4.csv')
%-------------------------------------------------------------------------------
tVaryingR1 = csvread('/mnt/dados/Meus Documentos/Estudo/Mestrado/Repositório/trunk/Material pesquisa/Leituras de sensores/Controle/Rotação dos motores/Entradas/throttle-varyingSignal-stable-rotor1.csv')
tVaryingR2 = csvread('/mnt/dados/Meus Documentos/Estudo/Mestrado/Repositório/trunk/Material pesquisa/Leituras de sensores/Controle/Rotação dos motores/Entradas/throttle-varyingSignal-stable-rotor2.csv')
tVaryingR3 = csvread('/mnt/dados/Meus Documentos/Estudo/Mestrado/Repositório/trunk/Material pesquisa/Leituras de sensores/Controle/Rotação dos motores/Entradas/throttle-varyingSignal-stable-rotor3.csv')
tVaryingR4 = csvread('/mnt/dados/Meus Documentos/Estudo/Mestrado/Repositório/trunk/Material pesquisa/Leituras de sensores/Controle/Rotação dos motores/Entradas/throttle-varyingSignal-stable-rotor4.csv')
rVaryingR1 = csvread('/mnt/dados/Meus Documentos/Estudo/Mestrado/Repositório/trunk/Material pesquisa/Leituras de sensores/Controle/Rotação dos motores/Saídas/revolutions-varyingSignal-stable-rotor1.csv')
rVaryingR2 = csvread('/mnt/dados/Meus Documentos/Estudo/Mestrado/Repositório/trunk/Material pesquisa/Leituras de sensores/Controle/Rotação dos motores/Saídas/revolutions-varyingSignal-stable-rotor2.csv')
rVaryingR3 = csvread('/mnt/dados/Meus Documentos/Estudo/Mestrado/Repositório/trunk/Material pesquisa/Leituras de sensores/Controle/Rotação dos motores/Saídas/revolutions-varyingSignal-stable-rotor3.csv')
rVaryingR4 = csvread('/mnt/dados/Meus Documentos/Estudo/Mestrado/Repositório/trunk/Material pesquisa/Leituras de sensores/Controle/Rotação dos motores/Saídas/revolutions-varyingSignal-stable-rotor4.csv')
